add new columns to InvoiceEntityListBuilder and zip function
ParallelDevs/e_invoice_cr pull request #23
Opened 2018-09-27 18:27 UTC by k-vargas

Se agregan nuevos valores al listado de entidades de factura en la clase InvoiceEntityListBuilder.
Además, uno de estas columnas contiene un link, el cual llama a una función en el controller, el cual descarga en un archivo comprimido .ZIP el PDF y los 2 archivos XML.

2018-10-11 00:02 UTC, k-vargas commented
@danielnv18 hay cambios que se deban realizar en este PR?

2018-10-11 17:24 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +    $uri = $uri . '/sites/default/files/';
No use rutas estaticas para guardar archivos. estas rutas puede que no existan. Use el API FileEntity de drupal para  guardar y crear archivos

2018-10-11 17:24 UTC, danielnv18 commented on modules/invoice_entity/config/schema/invoice_entity.schema.yml
> -   invoice_number:
Estas borrando una columna. Si un usuario tiene eso en esa columna, se va a perder. Si esta info aun es valida, haga un script de migracion para sitios existentes. Este schema solamente corre cuando se instala un sitio

2018-10-11 17:24 UTC, danielnv18 commented on modules/invoice_entity/src/Form/InvoiceEntityForm.php
> +    $consecutive = substr($this->entity->get('field_consecutive_number')->getValue()[0]['value'], 0, -10) . $invoice_service->getDocumentNumber();
Cual es el proposito de este codigo?

2018-10-11 17:24 UTC, danielnv18 commented on modules/invoice_entity/src/InvoiceEntityListBuilder.php
> +      $row['credit'] = 'None';
use el metodo de traduccion

2018-10-16 23:38 UTC, k-vargas commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +    $uri = $uri . '/sites/default/files/';
Una pregunta @danielnv18 es que esa ruta no es para crear archivos, sino más bien para cargarlos, específicamente para adjuntar al .ZIP los archivos .PDF y .XML que ya se encuentran creados, por otra funcionalidad aparte.
Que procede entonces?

2018-10-18 14:01 UTC, danielnv18 requested changes

2018-10-18 14:01 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +    $uri = DRUPAL_ROOT . '/sites/default/files/';
No use rutas estaticas para el URI. La ruta donde se guardan los archivos puede cambiar

2018-10-18 14:01 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +    $zip = new \ZipArchive();
Use el API de Drupal para crear el zip

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/js/invoice-rows.js
> +  $(document).on("change", "#edit-type-of", function (event) {
No agregue el evento a todo el documento. Hagalo al input o elemento directamente

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +  public function createZipFile($id) {
Agregue documentacion de lo que esta pasando en la funcion

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +   * {@inheritdoc}
ponga el comentario correspondiente a la funcion. El parent class no tiene este metodo

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +   * {@inheritdoc}
ponga el comentario correspondiente a la funcion. El parent class no tiene este metodo

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +   * {@inheritdoc}
ponga el comentario correspondiente a la funcion. El parent class no tiene este metodo

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +    $document_type = $_POST['type'];
No use $_POST para obtener el resultado de un post. Use `\Drupal::request()`

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +    $invoice_service = \Drupal::service($type);
agregue validacion en caso de que el type no exista

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/src/Controller/InvoiceEntityController.php
> +    switch ($type_of) {
Este codigo lo he visto en varios lugares. Pongalo en un servicio

2018-10-25 22:12 UTC, danielnv18 commented on modules/invoice_entity/js/invoice-rows.js
> +  $(document).on("change", "#edit-type-of", function (event) {
Cual es el proposito del aja?

2018-10-30 16:30 UTC, danielnv18 requested changes

2018-10-30 16:30 UTC, danielnv18 commented on modules/invoice_entity/templates/invoice-entity.html.twig
> +    <h2>{{ invoice.document_type|t }}</h2>
Quitele el filtro `|t`. como ahora es una variable y no tiene texto fijo, no vale la pena traducirlo

2018-10-30 16:30 UTC, danielnv18 commented on modules/invoice_entity/invoice_entity.routing.yml
> +    _title: 'Descargar'
El titulo tiene que estar en ingles

2018-10-30 16:30 UTC, danielnv18 commented on modules/invoice_entity/invoice_entity.routing.yml
> +    _permission: 'access content'
Pongale un permiso mas adecuado.

2018-10-30 21:47 UTC, danielnv18 approved these changes

2018-10-30 21:47 UTC, merged