fix errors and add validations in the modules
ParallelDevs/e_invoice_cr pull request #31
Opened 2018-11-01 17:41 UTC by k-vargas

Posterior a mezclar todos los PR, se hicieron pruebas generales de todos los módulos para corroborar que funcionara correctamente.
Una vez realizadas las pruebas, se detectaron varios errores que se corrigieron de manera inmediata.

2018-11-01 19:50 UTC, danielnv18 requested changes

2018-11-01 19:50 UTC, danielnv18 commented on modules/invoice_email/src/EventSubscriber/InvoiceEmailEventSubscriber.php
> +        $user_current = $entity->get('user_id')->getValue()[0]['target_id'];
pongale un nombre correspondiente a la variables. Ya no es `current user`

2018-11-01 19:50 UTC, danielnv18 commented on modules/invoice_entity/src/InvoiceService.php
> +          $user_current = $entity->get('user_id')->getValue()[0]['target_id'];
pongale un nombre correspondiente a la variables. Ya no es `current user`

2018-11-01 19:50 UTC, danielnv18 commented on modules/invoice_received_entity/src/ImportXMLFromEmail.php
> +    $query = $connection->query('SELECT * FROM ' . $table_name . ' WHERE id = (SELECT MAX(id) FROM ' . $table_name . ')');
no use el `connection->query`. 
Este seguro que no exista un api que le permita hacer algo parecido.
si de verdad no hay algo parecido en drupal, entonces use el select() y no el query()

2018-11-01 19:50 UTC, danielnv18 commented on modules/invoice_received_entity/src/ImportXMLFromEmail.php
> +    $newData = $this->getNewData('invoice_received_entity');
use Snake case para nombrar las variables

2018-11-01 19:57 UTC, danielnv18 requested changes

2018-11-01 19:57 UTC, danielnv18 commented on modules/invoice_received_entity/src/ImportXMLFromEmail.php
> +    $uuid_service = \Drupal::service('uuid');
si la clase es un servicio, entonces use el metodo `dependecy injection` para insertar el servicio

2018-11-05 21:38 UTC, k-vargas commented on modules/customer_entity/src/Form/CustomerEntityForm.php
> +
Agregar validación para longitud de texto en un formulario.

2018-11-05 21:38 UTC, k-vargas commented on modules/invoice_entity/src/InvoiceService.php
> +          $user_current = $entity->get('user_id')->getValue()[0]['target_id'];
Cuando se ejecuta un cron job para validar las facturas que quedaron pendientes, se obtiene el valor del current_user, pero este no coincide con el usuario que creo la factura ni los documentos. Por lo que se obtiene el user_id que tiene referenciado la entidad. (Esto también se hace a la hora de adjuntar los datos para enviar el correo al cliente, ya que ocurría el mismo problema).

2018-11-05 21:38 UTC, k-vargas commented on modules/invoice_received_entity/src/ImportXMLFromEmail.php
> +
Se crea una nueva función para obtener los datos de los entity_keys que utilizan las entidades invoice_received_entity y provider_entity.

2018-11-05 21:38 UTC, k-vargas commented on modules/invoice_received_entity/src/Form/InvoiceReceivedEntityForm.php
> +        }
Se hace una validación a la hora de subir un archivo, para asegurarse que contenga todos los datos que se requieren para crear la entidad.

2018-11-07 14:40 UTC, merged