Nuevos cambios al módulos
ParallelDevs/e_invoice_cr pull request #33
Opened 2018-11-13 16:03 UTC by k-vargas

Se agrega un hook_update para el módulo invoice_entity, para que todas las entidades previamente guardadas, tomen los archivos referentes a la factura y los guarde como FileEntity, para que así no tengan problemas con la funcionalidad de descargar zip.
Por otro lado, se agrega nuevas validaciones para el formulario del invoice_received_entity, basados en diferentes escenarios que pueden ocurrir cuando se intenta insertar una nueva factura recibida.

2018-11-14 02:26 UTC, danielnv18 requested changes
El codigo carece de comentarios. Por favor documente el codigo

2018-11-14 17:05 UTC, k-vargas commented
@danielnv18 ya está aplicado los cambios solicitados

2018-11-15 14:02 UTC, danielnv18 approved these changes

2018-11-15 14:02 UTC, danielnv18 commented on modules/invoice_entity/invoice_entity.install
> +      $entity = InvoiceEntity::load($nid->id);
use https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Entity.php/function/Entity%3A%3AloadMultiple/8.2.x para cargar todos los nodos y no cargar uno por uno

2018-11-15 15:48 UTC, merged